services:
  - type: web
    name: ronak-tanna-portfolio
    runtime: static
    branch: main
    buildCommand: npm ci && npm run build
    staticPublishPath: ./out
    autoDeployTrigger: commit
    envVars:
      - key: NODE_VERSION
        value: 22.22.1
